### ISSUE TITLE
How do I configure this using Yaml meta drivers instead of php annotations ?

### ISSUE THREAD

**Issue by Evertt** [laravel-doctrine/acl#11]

**Comment by patrickbrouwers** [comment]
Just write the relations in yaml like you would normally do.

**Comment by FoxxMD** [comment]
Here is an example of the Role entity from my app:

``` yaml
App\Models\Role:
  type: entity
  table: roles
  id:
    id:
      type: integer
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    name:
      type: string
      nullable: false
  manyToMany:
    permissions:
      targetEntity: App\Models\Permission
      joinTable:
        name: rolePermissions
        joinColumn:
          name: permissionId
          referencedColumnName: id
        inverseJoinColumn:
          name: roleId
          referencedColumnName: id
```

But @patrickbrouwers is right -- writing these yaml mappings is no different from a normal entity. Just make sure you are implementing the contracts on whatever entity you use.
